services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commemyhome_v2
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
